stages:
  - test
  - build

test:
  image: mcr.microsoft.com/dotnet/core/sdk:2.1
  stage: test
  script:
    - dotnet build
    - dotnet test

build-dev:
  only:
    - master
  image: mcr.microsoft.com/dotnet/core/sdk:2.1
  stage: build
  script:
    - dotnet build -p:OutDir="$(pwd)/build_output"
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
    expire_in: 52 weeks
    paths:
      - build_output/*

build-tag:
  only:
    - tags
  image: mcr.microsoft.com/dotnet/core/sdk:2.1
  stage: build
  script:
    - dotnet build --configuration Release -p:Version="$CI_COMMIT_TAG" -p:OutDir="$(pwd)/build_output"
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - build_output/*
