name: .NET

on:
  push:
    branches: master

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.302'  
      - run: | 
          dotnet build Promaster.Primitives/Promaster.Primitives.csproj
          dotnet build Promaster.Primitives.Test/Promaster.Primitives.Test.csproj
