name: .NET

on:
  push:
    branches: master

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.302'
      - name: Install dependencies
        run: | 
          dotnet restore Promaster.Primitives.Test/Promaster.Primitives.Test.csproj
      - name: Build
        run: | 
          dotnet build Promaster.Primitives/Promaster.Primitives.csproj
          dotnet build Promaster.Primitives.Test/Promaster.Primitives.Test.csproj
      - name: Test
        run: | 
          dotnet test Promaster.Primitives.Test/Promaster.Primitives.Test.csproj

