name: .NET

on:
  push:
    branches: master

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.0.100-rc1-014190'
      - run: dotnet build -p:OutDir="$(pwd)/build_output"
      
