name: .NET

on:
  push:
    branches: master

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.302'
      - name: Test    
      - run: | 
          dotnet run --project Promaster.Primitives/Promaster.Primitives.csproj
